name: .NET Publish

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Publish Chess
      run: dotnet publish Chess\Chess.csproj -p:PublishProfile=FolderProfile

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: WPF-Chess
        path: Chess\bin\x64\Release\net8.0-windows\publish\win-x64\Chess.exe
